
public class PersonDefaultConstructor {

    public PersonDefaultConstructor() {
        System.out.println("Person object created!");
    }

    public static void main(String[] args) {
        PersonDefaultConstructor person = new PersonDefaultConstructor(); // Calls the default constructor
        System.out.println(person.hashCode()); // PersonDefaultConstructor@4517d9a3
        // A hash code is a numerical value generated by a hash function. In Java, it is a 32-bit integer that represents the memory address or some unique identifier of an object.
    }
}
